---


- name: "Baixando o Script de Instalacao do Node.js versão {{ nodejs_version }}"
  get_url:
   url: "https://deb.nodesource.com/setup_{{ nodejs_versions[nodejs_version] }}"
   dest: "/tmp/setup_nodejs.sh"
  become: true
  tags:
   - nodejs


- name: "Executando o Script de Instalacao do Node.js versão {{ nodejs_version }}"
  command: "bash /tmp/setup_nodejs.sh"
  become: true
  tags:
   - nodejs


- name: "Instalando o Node.js versão {{ nodejs_version }}"
  apt:
    name: nodejs
    state: present
    update_cache: yes
  become: true
  tags:
    - nodejs
