---

- name: "Instalando as dependencias do Node.js"
  dnf:
    name: "{{ node_deps }}"
    state: present
  become: true
  tags:
    - nodejs


- name: "Baixando o Script de Instalacao do Node.js versão {{ nodejs_version }}"
  get_url:
   url: "https://rpm.nodesource.com/setup_{{ nodejs_versions[nodejs_version] }}"
   dest: "/tmp/setup_nodejs.sh"
   mode: 0755
  become: true
  tags:
   - nodejs


- name: "Executando o Script de Instalacao do Node.js versão {{ nodejs_version }}"
  shell: "/tmp/setup_nodejs.sh"
  become: true
  tags:
   - nodejs


- name: "Instalando o Node.js versão {{ nodejs_version }}"
  dnf:
    name: nodejs
    state: present
  become: true
  tags:
    - nodejs